name: OSCAL CAT CI/CD
on:
  push:
    branches:
    - main
    - develop
    - "release-*"
  pull_request:
    branches:
    - main
    - develop
    - "release-*"
jobs:
  ci:
    uses: ./.github/workflows/build.yml
  cd-pr-only:
    if: github.event_name == 'pull_request'
    needs: ci
    uses: ./.github/workflows/deploy.yml
    with:
      commit_resources: false
  cd-full:
    if: github.event_name == 'push'
    needs: ci
    uses: ./.github/workflows/deploy.yml
    with:
      commit_resources: true
    secrets:
      access_token: ${{ secrets.COMMIT_TOKEN }}
  sbom-license-analysis:
    needs: ci
    uses: ./.github/workflows/generate-license-reports.yml
